<?php
require_once __DIR__ . '/../../vendor/autoload.php';
require_once __DIR__ . '/../config/Mailer.php';
require_once __DIR__ . '/../config/Payment.php';

use PHPMailer\PHPMailer\PHPMailer;
use PHPMailer\PHPMailer\SMTP;
use PHPMailer\PHPMailer\Exception;

function buildNotificationEmail($title, $message) {
    return "<html><body>"
        . "<div style='font-family: Arial, sans-serif; max-width: 700px; margin: auto;'>"
        . "<h2 style='color:#2f4f4f;'>" . htmlentities($title) . "</h2>"
        . "<p style='font-size:16px; line-height:1.5; color:#333;'>" . nl2br(htmlentities($message)) . "</p>"
        . "<hr style='border:none; border-top:1px solid #eee;' />"
        . "<p style='font-size:14px; color:#666;'>This notification was generated by the MarketPlace system.</p>"
        . "</div></body></html>";
}

function sendMarketplaceEmail($toEmail, $toName, $subject, $htmlBody) {
    $config = MailerConfig::getConfig();
    $mail = new PHPMailer(true);

    try {
        if ($config['is_smtp']) {
            $mail->isSMTP();
            $mail->Host = $config['host'];
            $mail->SMTPAuth = true;
            $mail->Username = $config['username'];
            $mail->Password = $config['password'];
            $mail->SMTPSecure = $config['smtp_secure'];
            $mail->Port = $config['port'];
            $mail->SMTPDebug = $config['smtp_debug'];
        } else {
            $mail->isMail();
        }

        $mail->setFrom($config['from_email'], $config['from_name']);
        $mail->addAddress($toEmail, $toName);
        $mail->addReplyTo($config['reply_to'], 'Marketplace Support');
        $mail->isHTML(true);
        $mail->Subject = $subject;
        $mail->Body = $htmlBody;
        $mail->AltBody = strip_tags($htmlBody);
        $mail->CharSet = 'UTF-8';

        $mail->send();
        return true;
    } catch (Exception $e) {
        error_log('Mailer Error: ' . $e->getMessage());
        return false;
    }
}

function logNotification($db, $recipientId, $recipientRole, $subject, $message, $referenceId = null, $referenceType = null, $emailTo = null, $status = 'sent') {
    if (!$db) {
        return false;
    }

    try {
        $notificationId = 'NOTIF-' . bin2hex(random_bytes(5));
        $insert = $db->prepare('INSERT INTO notification (notification_id, user_id, recipient_role, subject, message, reference_type, reference_id, email_to, status, sent_at, created_at) VALUES (:notification_id, :user_id, :recipient_role, :subject, :message, :reference_type, :reference_id, :email_to, :status, NOW(), NOW())');
        $insert->execute([
            ':notification_id' => $notificationId,
            ':user_id' => $recipientId,
            ':recipient_role' => $recipientRole,
            ':subject' => $subject,
            ':message' => $message,
            ':reference_type' => $referenceType,
            ':reference_id' => $referenceId,
            ':email_to' => $emailTo,
            ':status' => $status
        ]);
        return true;
    } catch (PDOException $e) {
        error_log('Notification log error: ' . $e->getMessage());
        return false;
    }
}

function sendGenericNotification($db, $recipientId, $recipientRole, $toEmail, $toName, $subject, $message, $referenceId = null, $referenceType = null) {
    $sent = sendMarketplaceEmail($toEmail, $toName, $subject, buildNotificationEmail($subject, $message));
    logNotification($db, $recipientId, $recipientRole, $subject, $message, $referenceId, $referenceType, $toEmail, $sent ? 'sent' : 'failed');
    return $sent;
}

function sendBuyerNotification($db, $recipientId, $toEmail, $toName, $subject, $message, $referenceId = null, $referenceType = null) {
    return sendGenericNotification($db, $recipientId, 'buyer', $toEmail, $toName, $subject, $message, $referenceId, $referenceType);
}

function sendSellerNotification($db, $recipientId, $toEmail, $toName, $subject, $message, $referenceId = null, $referenceType = null) {
    return sendGenericNotification($db, $recipientId, 'seller', $toEmail, $toName, $subject, $message, $referenceId, $referenceType);
}

function sendProviderNotification($db, $recipientId, $toEmail, $toName, $subject, $message, $referenceId = null, $referenceType = null) {
    return sendGenericNotification($db, $recipientId, 'provider', $toEmail, $toName, $subject, $message, $referenceId, $referenceType);
}

function sendAdminNotification($db, $recipientId, $subject, $message, $referenceId = null, $referenceType = null) {
    $config = PaymentConfig::getConfig();
    $adminEmail = $config['default_admin_email'] ?? $config['reply_to'] ?? 'admin@marketplace.local';
    return sendGenericNotification($db, $recipientId, 'admin', $adminEmail, 'Marketplace Admin', $subject, $message, $referenceId, $referenceType);
}
?>
