<?php
require_once __DIR__ . '/../../vendor/autoload.php';
require_once __DIR__ . '/../config/Mailer.php';

use PHPMailer\PHPMailer\PHPMailer;
use PHPMailer\PHPMailer\SMTP;
use PHPMailer\PHPMailer\Exception;

function buildNotificationEmail($title, $message) {
    return "<html><body>"
        . "<div style='font-family: Arial, sans-serif; max-width: 700px; margin: auto;'>"
        . "<h2 style='color:#2f4f4f;'>" . htmlentities($title) . "</h2>"
        . "<p style='font-size:16px; line-height:1.5; color:#333;'>" . nl2br(htmlentities($message)) . "</p>"
        . "<hr style='border:none; border-top:1px solid #eee;' />"
        . "<p style='font-size:14px; color:#666;'>This notification was generated by the MarketPlace system.</p>"
        . "</div></body></html>";
}

function sendMarketplaceEmail($toEmail, $toName, $subject, $htmlBody) {
    $config = MailerConfig::getConfig();
    $mail = new PHPMailer(true);

    try {
        if ($config['is_smtp']) {
            $mail->isSMTP();
            $mail->Host = $config['host'];
            $mail->SMTPAuth = true;
            $mail->Username = $config['username'];
            $mail->Password = $config['password'];
            $mail->SMTPSecure = $config['smtp_secure'];
            $mail->Port = $config['port'];
            $mail->SMTPDebug = $config['smtp_debug'];
        } else {
            $mail->isMail();
        }

        $mail->setFrom($config['from_email'], $config['from_name']);
        $mail->addAddress($toEmail, $toName);
        $mail->addReplyTo($config['reply_to'], 'Marketplace Support');
        $mail->isHTML(true);
        $mail->Subject = $subject;
        $mail->Body = $htmlBody;
        $mail->AltBody = strip_tags($htmlBody);
        $mail->CharSet = 'UTF-8';

        $mail->send();
        return true;
    } catch (Exception $e) {
        error_log('Mailer Error: ' . $e->getMessage());
        return false;
    }
}
?>
